# Maven


# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
- master

pool:
  vmImage: 'Ubuntu-16.04'
variables:
  dockerId: afrin123 # Replace with your Docker ID for Docker Hub or the admin user name for the Azure Container Registry
  imageName: new
steps:
- task: SonarQubePrepare@4
  inputs:
    SonarQube: '11b7a636-8cc8-4b9c-ac1f-852cc7de1401'
    scannerMode: 'Other'


- task: Maven@3
  inputs:
    mavenPomFile: 'pom.xml'
    mavenOptions: '-Xmx3072m'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '1.11'
    jdkArchitectureOption: 'x64'
    publishJUnitResults: false
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    goals: 'package'
- script: |
    #docker build -t $(dockerId)/$(imageName) .
    docker login -u $(dockerId) -p hello123
    docker build -t myapp .
    docker run -it --rm -p 8888:8080 myapp
    #docker push $(dockerId)/$(imageName)

